'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('RefBoardAPI', {
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  getDefaultExportDir: () => ipcRenderer.invoke('get-default-export-dir'),
  getProcessMemoryInfo: () => ipcRenderer.invoke('get-process-memory-info'),
  writeExportFiles: (dir, files) => ipcRenderer.invoke('write-export-files', { dir, files }),
  stageDragOut: (files) => ipcRenderer.invoke('stage-drag-out', { files }),
  startDragOut: (paths, icon) => ipcRenderer.invoke('start-drag-out', { paths, icon }),
  saveBoardFile: (defaultName, data, filePath, forceDialog = false) => ipcRenderer.invoke('save-board-file', { defaultName, data, filePath, forceDialog }),
  beginBoardSave: (defaultName, filePath, core, preview, forceDialog = false, imageRefs = []) => ipcRenderer.invoke('begin-board-save', { defaultName, filePath, forceDialog, core, preview, imageRefs }),
  appendBoardSaveImage: (token, image, data) => ipcRenderer.invoke('append-board-save-image', { token, image, data }),
  appendBoardSaveImages: (token, images) => ipcRenderer.invoke('append-board-save-images', { token, images }),
  finishBoardSave: (token) => ipcRenderer.invoke('finish-board-save', token),
  abortBoardSave: (token) => ipcRenderer.invoke('abort-board-save', token),
  openBoardDialog: () => ipcRenderer.invoke('open-board-dialog'),
  readBoardFile: (filePath) => ipcRenderer.invoke('read-board-file', filePath),
  beginBoardOpen: (filePath) => ipcRenderer.invoke('begin-board-open', filePath),
  readBoardOpenImage: (token, index) => ipcRenderer.invoke('read-board-open-image', { token, index }),
  readBoardOpenImages: (token, indexes) => ipcRenderer.invoke('read-board-open-images', { token, indexes }),
  finishBoardOpen: (token) => ipcRenderer.invoke('finish-board-open', token),
  recoverBoardFile: (filePath) => ipcRenderer.invoke('recover-board-file', filePath),
  getRecentWorks: () => ipcRenderer.invoke('get-recent-works'),
  addRecentWork: (entry) => ipcRenderer.invoke('add-recent-work', entry),
  touchRecentWorkEdited: (filePath) => ipcRenderer.invoke('touch-recent-work-edited', filePath),
  removeRecentWork: (filePath) => ipcRenderer.invoke('remove-recent-work', filePath),
  setRecentWorkPinned: (filePath, pinned) => ipcRenderer.invoke('set-recent-work-pinned', { filePath, pinned }),
  renameRecentWork: (filePath, name) => ipcRenderer.invoke('rename-recent-work', { filePath, name }),
  revealBoardFile: (filePath) => ipcRenderer.invoke('reveal-board-file', filePath),
  getThumbnailData: (filename) => ipcRenderer.invoke('get-thumbnail-data', filename),
  getBoardPreview: (filePath) => ipcRenderer.invoke('get-board-preview', filePath),
  writeBoardPreview: (filePath, preview) => ipcRenderer.invoke('write-board-preview', { filePath, preview }),
  getPendingOpenPath: () => ipcRenderer.invoke('get-pending-open-path'),
  readClipboardImage: () => ipcRenderer.invoke('clipboard-read-image'),
  writeClipboardNotes: (payload, plainText) => ipcRenderer.invoke('clipboard-write-notes', { payload, plainText }),
  readClipboardNotes: () => ipcRenderer.invoke('clipboard-read-notes'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onCloseRequest: (cb) => ipcRenderer.on('close-request', () => cb()),
  onOpenBoardPath: (cb) => ipcRenderer.on('open-board-path', (_e, filePath) => cb(filePath)),
  confirmClose: () => ipcRenderer.send('close-confirmed'),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  windowMaximize: () => ipcRenderer.send('window-maximize'),
  windowClose: () => ipcRenderer.send('window-close'),
  isWindowMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  onWindowMaximizeChange: (cb) => ipcRenderer.on('window-maximize-changed', (_e, maximized) => cb(maximized)),
  pinGetState: () => ipcRenderer.invoke('pin-get-state'),
  pinSetAlways: () => ipcRenderer.invoke('pin-set-always'),
  pinSetAbove: (id) => ipcRenderer.invoke('pin-set-above', { id }),
  pinClear: () => ipcRenderer.invoke('pin-clear'),
  pinListWindows: () => ipcRenderer.invoke('pin-list-windows'),
  onPinStateChange: (cb) => ipcRenderer.on('pin-state-changed', (_e, state) => cb(state)),
  onPinOpenAbove: (cb) => ipcRenderer.on('pin-open-above', () => cb()),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  checkWhatsNew: () => ipcRenderer.invoke('whats-new-check'),
  getCurrentWhatsNew: () => ipcRenderer.invoke('whats-new-current'),
  dismissWhatsNew: () => ipcRenderer.invoke('whats-new-dismiss'),
  getAppIconDataUrl: () => ipcRenderer.invoke('get-app-icon-data-url'),
  openBoardInNewWindow: (filePath = null) => ipcRenderer.invoke('open-board-window', { filePath }),
  getBoardWindowCount: () => ipcRenderer.invoke('get-board-window-count'),
  updaterInit: (opts) => ipcRenderer.invoke('updater-init', opts),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
});
