'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('RefBoardAPI', {
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  getDefaultExportDir: () => ipcRenderer.invoke('get-default-export-dir'),
  getProcessMemoryInfo: () => ipcRenderer.invoke('get-process-memory-info'),
  writeExportFiles: (dir, files) => ipcRenderer.invoke('write-export-files', { dir, files }),
  saveBoardFile: (defaultName, data, filePath) => ipcRenderer.invoke('save-board-file', { defaultName, data, filePath }),
  beginBoardSave: (defaultName, filePath, core, preview) => ipcRenderer.invoke('begin-board-save', { defaultName, filePath, core, preview }),
  appendBoardSaveImage: (token, image, data) => ipcRenderer.invoke('append-board-save-image', { token, image, data }),
  finishBoardSave: (token) => ipcRenderer.invoke('finish-board-save', token),
  abortBoardSave: (token) => ipcRenderer.invoke('abort-board-save', token),
  openBoardDialog: () => ipcRenderer.invoke('open-board-dialog'),
  readBoardFile: (filePath) => ipcRenderer.invoke('read-board-file', filePath),
  beginBoardOpen: (filePath) => ipcRenderer.invoke('begin-board-open', filePath),
  readBoardOpenImage: (token, index) => ipcRenderer.invoke('read-board-open-image', { token, index }),
  finishBoardOpen: (token) => ipcRenderer.invoke('finish-board-open', token),
  getRecentWorks: () => ipcRenderer.invoke('get-recent-works'),
  addRecentWork: (entry) => ipcRenderer.invoke('add-recent-work', entry),
  touchRecentWorkEdited: (filePath) => ipcRenderer.invoke('touch-recent-work-edited', filePath),
  removeRecentWork: (filePath) => ipcRenderer.invoke('remove-recent-work', filePath),
  getThumbnailData: (filename) => ipcRenderer.invoke('get-thumbnail-data', filename),
  getPendingOpenPath: () => ipcRenderer.invoke('get-pending-open-path'),
  readClipboardImage: () => ipcRenderer.invoke('clipboard-read-image'),
  writeClipboardNotes: (payload, plainText) => ipcRenderer.invoke('clipboard-write-notes', { payload, plainText }),
  readClipboardNotes: () => ipcRenderer.invoke('clipboard-read-notes'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onCloseRequest: (cb) => ipcRenderer.on('close-request', () => cb()),
  onOpenBoardPath: (cb) => ipcRenderer.on('open-board-path', (_e, filePath) => cb(filePath)),
  confirmClose: () => ipcRenderer.send('close-confirmed'),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  windowMaximize: () => ipcRenderer.send('window-maximize'),
  windowClose: () => ipcRenderer.send('window-close'),
  isWindowMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  onWindowMaximizeChange: (cb) => ipcRenderer.on('window-maximize-changed', (_e, maximized) => cb(maximized)),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  checkWhatsNew: () => ipcRenderer.invoke('whats-new-check'),
  dismissWhatsNew: () => ipcRenderer.invoke('whats-new-dismiss'),
  getAppIconDataUrl: () => ipcRenderer.invoke('get-app-icon-data-url'),
  updaterInit: (opts) => ipcRenderer.invoke('updater-init', opts),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
});
