'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('RefBoardAPI', {
  chooseFolder: () => ipcRenderer.invoke('choose-folder'),
  getDefaultExportDir: () => ipcRenderer.invoke('get-default-export-dir'),
  getProcessMemoryInfo: () => ipcRenderer.invoke('get-process-memory-info'),
  beginAnimaticExport: (settings) => ipcRenderer.invoke('begin-animatic-export', settings),
  appendAnimaticFrame: (token, frame) => ipcRenderer.invoke('append-animatic-frame', { token, frame }),
  appendAnimaticAudio: (token, audio) => ipcRenderer.invoke('append-animatic-audio', { token, audio }),
  finishAnimaticExport: (token) => ipcRenderer.invoke('finish-animatic-export', token),
  abortAnimaticExport: (token) => ipcRenderer.invoke('abort-animatic-export', token),
  beginPremiereExport: (settings) => ipcRenderer.invoke('begin-premiere-export', settings),
  appendPremiereExportAsset: (token, asset) => ipcRenderer.invoke('append-premiere-export-asset', { token, asset }),
  finishPremiereExport: (token, xml) => ipcRenderer.invoke('finish-premiere-export', { token, xml }),
  abortPremiereExport: (token) => ipcRenderer.invoke('abort-premiere-export', token),
  beginAfterEffectsExport: (settings) => ipcRenderer.invoke('begin-after-effects-export', settings),
  appendAfterEffectsExportAsset: (token, asset) => ipcRenderer.invoke('append-after-effects-export-asset', { token, asset }),
  finishAfterEffectsExport: (token, script) => ipcRenderer.invoke('finish-after-effects-export', { token, script }),
  abortAfterEffectsExport: (token) => ipcRenderer.invoke('abort-after-effects-export', token),
  writeExportFiles: (dir, files) => ipcRenderer.invoke('write-export-files', { dir, files }),
  saveBoardFile: (defaultName, data, filePath, forceDialog = false) => ipcRenderer.invoke('save-board-file', { defaultName, data, filePath, forceDialog }),
  beginBoardSave: (defaultName, filePath, core, preview, forceDialog = false) => ipcRenderer.invoke('begin-board-save', { defaultName, filePath, forceDialog, core, preview }),
  appendBoardSaveImage: (token, image, data) => ipcRenderer.invoke('append-board-save-image', { token, image, data }),
  finishBoardSave: (token) => ipcRenderer.invoke('finish-board-save', token),
  abortBoardSave: (token) => ipcRenderer.invoke('abort-board-save', token),
  openBoardDialog: () => ipcRenderer.invoke('open-board-dialog'),
  readBoardFile: (filePath) => ipcRenderer.invoke('read-board-file', filePath),
  beginBoardOpen: (filePath) => ipcRenderer.invoke('begin-board-open', filePath),
  readBoardOpenImage: (token, index) => ipcRenderer.invoke('read-board-open-image', { token, index }),
  finishBoardOpen: (token) => ipcRenderer.invoke('finish-board-open', token),
  getRecentWorks: () => ipcRenderer.invoke('get-recent-works'),
  addRecentWork: (entry) => ipcRenderer.invoke('add-recent-work', entry),
  touchRecentWorkEdited: (filePath) => ipcRenderer.invoke('touch-recent-work-edited', filePath),
  removeRecentWork: (filePath) => ipcRenderer.invoke('remove-recent-work', filePath),
  getThumbnailData: (filename) => ipcRenderer.invoke('get-thumbnail-data', filename),
  getBoardPreview: (filePath) => ipcRenderer.invoke('get-board-preview', filePath),
  writeBoardPreview: (filePath, preview) => ipcRenderer.invoke('write-board-preview', { filePath, preview }),
  getPendingOpenPath: () => ipcRenderer.invoke('get-pending-open-path'),
  readClipboardImage: () => ipcRenderer.invoke('clipboard-read-image'),
  writeClipboardNotes: (payload, plainText) => ipcRenderer.invoke('clipboard-write-notes', { payload, plainText }),
  readClipboardNotes: () => ipcRenderer.invoke('clipboard-read-notes'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  onCloseRequest: (cb) => ipcRenderer.on('close-request', () => cb()),
  onOpenBoardPath: (cb) => ipcRenderer.on('open-board-path', (_e, filePath) => cb(filePath)),
  confirmClose: () => ipcRenderer.send('close-confirmed'),
  windowMinimize: () => ipcRenderer.send('window-minimize'),
  windowMaximize: () => ipcRenderer.send('window-maximize'),
  windowClose: () => ipcRenderer.send('window-close'),
  isWindowMaximized: () => ipcRenderer.invoke('window-is-maximized'),
  onWindowMaximizeChange: (cb) => ipcRenderer.on('window-maximize-changed', (_e, maximized) => cb(maximized)),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  checkWhatsNew: () => ipcRenderer.invoke('whats-new-check'),
  getCurrentWhatsNew: () => ipcRenderer.invoke('whats-new-current'),
  dismissWhatsNew: () => ipcRenderer.invoke('whats-new-dismiss'),
  getAppIconDataUrl: () => ipcRenderer.invoke('get-app-icon-data-url'),
  updaterInit: (opts) => ipcRenderer.invoke('updater-init', opts),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
});
